# Generated by Django 3.1.7 on 2021-03-24 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('headline', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('clap_count', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('headline', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('clap_count', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['pub_date'],
            },
        ),
    ]
