# Generated by Django 3.1.7 on 2021-03-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='album', verbose_name='Image')),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='bulletin',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Bulletin', 'verbose_name_plural': 'Bulletins'},
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('headline', models.CharField(max_length=200)),
                ('pub_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('clap_count', models.IntegerField(default=0)),
                ('images', models.ManyToManyField(blank=True, related_name='album_images', to='article.AlbumImage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
