# Generated by Django 3.1.7 on 2021-03-25 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210325_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.RemoveField(
            model_name='album',
            name='images',
        ),
        migrations.AddField(
            model_name='albumimage',
            name='album',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.album'),
            preserve_default=False,
        ),
    ]
