# Generated by Django 3.2 on 2021-04-24 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(blank=True, null=True, upload_to='')),
                ('url', models.URLField(blank=True, help_text='Company URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', help_text='County', max_length=150)),
                ('state', models.CharField(blank=True, default='', help_text='Region/State', max_length=150)),
                ('district', models.CharField(blank=True, default='', help_text='District', max_length=150)),
                ('town_city', models.CharField(blank=True, default='', help_text='Village/Taluka/Town/City.', max_length=150)),
                ('street_name', models.CharField(blank=True, default='', help_text='Street name', max_length=255)),
                ('address_line', models.CharField(blank=True, help_text='House name/number', max_length=255)),
                ('post_code', models.CharField(blank=True, default='', help_text='Post/ZIP code', max_length=15)),
                ('plus_code', models.CharField(blank=True, default='', help_text='Plus code (https://maps.google.com/pluscodes/)', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.company')),
            ],
            options={
                'ordering': ['company__name', 'country'],
            },
        ),
        migrations.CreateModel(
            name='JobAdvert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Job URL')),
                ('min_experience', models.IntegerField(default=0, help_text='Experience in years')),
                ('min_qualification', models.CharField(choices=[('btech', 'B.Tech'), ('mtech', 'M.Tech'), ('phd', 'PhD')], max_length=10)),
                ('min_salary', models.IntegerField(default=0)),
                ('max_salary', models.IntegerField(default=0)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('parttime', 'Part-time'), ('contract', 'Contract')], max_length=10)),
                ('last_date', models.DateField()),
                ('view_count', models.IntegerField(default=0)),
                ('company_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.companyaddress')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_date'],
            },
        ),
    ]
