# Generated by Django 3.1.7 on 2021-04-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_regions', '0002_data'),
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaddress',
            name='country',
            field=models.ForeignKey(help_text='Country', on_delete=django.db.models.deletion.CASCADE, to='country_regions.country'),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Region/State', on_delete=django.db.models.deletion.CASCADE, to='country_regions.region'),
        ),
        migrations.AlterField(
            model_name='jobadvert',
            name='last_date',
            field=models.DateField(),
        ),
    ]
