# Generated by Django 3.1.7 on 2021-04-05 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skills'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permanentaddress',
            options={'ordering': ['personal_profile']},
        ),
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'ordering': ['personal_profile']},
        ),
        migrations.AlterUniqueTogether(
            name='socialprofile',
            unique_together={('personal_profile', 'social_media')},
        ),
        migrations.CreateModel(
            name='ProfessionalSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.personalprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skills')),
            ],
            options={
                'ordering': ['personal_profile'],
                'unique_together': {('personal_profile', 'skill')},
            },
        ),
    ]
